#ifndef __color_h
#define __color_h

#include <SDL2/SDL.h>

// Link to colors : https://www.rapidtables.com/web/color/RGB_Color.html

extern SDL_Color color_black;
extern SDL_Color color_white;
extern SDL_Color color_red;
extern SDL_Color color_lime;
extern SDL_Color color_blue;
extern SDL_Color color_yellow;
extern SDL_Color color_cyan;
extern SDL_Color color_aqua;
extern SDL_Color color_magenta;
extern SDL_Color color_fuschia;
extern SDL_Color color_silver;
extern SDL_Color color_gray;
extern SDL_Color color_maroon;
extern SDL_Color color_olive;
extern SDL_Color color_green;
extern SDL_Color color_purple;
extern SDL_Color color_teal;
extern SDL_Color color_navy;
// Red variants
extern SDL_Color color_darkred;
extern SDL_Color color_brown;
extern SDL_Color color_firebrick;
extern SDL_Color color_crimson;
extern SDL_Color color_tomato;
extern SDL_Color color_coral;
extern SDL_Color color_indianred;
extern SDL_Color color_lightcoral;
extern SDL_Color color_darksalmon;
extern SDL_Color color_salmon;
extern SDL_Color color_lightsalmon;
extern SDL_Color color_orange;
extern SDL_Color color_darkorange;
extern SDL_Color color_moccasin;
extern SDL_Color color_navajowhite;
extern SDL_Color color_peachpuff;
// Yellow variants
extern SDL_Color color_gold;
extern SDL_Color color_darkgoldenrod;
extern SDL_Color color_goldenrod;
extern SDL_Color color_palegoldenrod;
extern SDL_Color color_darkkhaki;
extern SDL_Color color_khaki;
// Green variants
extern SDL_Color color_yellowgreen;
extern SDL_Color color_darkolivegreen;
extern SDL_Color color_olivedrab;
extern SDL_Color color_lawngreen;
extern SDL_Color color_chartreuse;
extern SDL_Color color_greenyellow;
extern SDL_Color color_darkgreen;
extern SDL_Color color_forestgreen;
extern SDL_Color color_limegreen;
extern SDL_Color color_lightgreen;
extern SDL_Color color_palegreen;
extern SDL_Color color_darkseagreen;
extern SDL_Color color_mediumspringgreen;
extern SDL_Color color_springgreen;
extern SDL_Color color_seagreen;
extern SDL_Color color_mediumaquamarine;
extern SDL_Color color_mediumseagreen;
extern SDL_Color color_honeydew;
// Blue variants
extern SDL_Color color_lightseagreen;
extern SDL_Color color_darkslategray;
extern SDL_Color color_darkcyan;
extern SDL_Color color_lightcyan;
extern SDL_Color color_darkturquoise;
extern SDL_Color color_turquoise;
extern SDL_Color color_mediumturquoise;
extern SDL_Color color_paleturquoise;
extern SDL_Color color_aquamarine;
extern SDL_Color color_powderblue;
extern SDL_Color color_cadetblue;
extern SDL_Color color_steelblue;
extern SDL_Color color_cornflowerblue;
extern SDL_Color color_deepskyblue;
extern SDL_Color color_dodgerblue;
extern SDL_Color color_lightblue;
extern SDL_Color color_skyblue;
extern SDL_Color color_lightskyblue;
extern SDL_Color color_midnightblue;
extern SDL_Color color_darkblue;
extern SDL_Color color_mediumblue;
extern SDL_Color color_royalblue;
extern SDL_Color color_lightsteelblue;
extern SDL_Color color_aliceblue;
extern SDL_Color color_azure;
// Purple variants
extern SDL_Color color_blueviolet;
extern SDL_Color color_indigo;
extern SDL_Color color_darkslateblue;
extern SDL_Color color_slateblue;
extern SDL_Color color_mediumslateblue;
extern SDL_Color color_mediumpurple;
extern SDL_Color color_darkmagenta;
extern SDL_Color color_darkviolet;
extern SDL_Color color_mediumorchid;
extern SDL_Color color_lavenderbush;
extern SDL_Color color_lavender;
// Pink variants
extern SDL_Color color_thistle;
extern SDL_Color color_plum;
extern SDL_Color color_violet;
extern SDL_Color color_orchid;
extern SDL_Color color_mediumvioletred;
extern SDL_Color color_palevioletred;
extern SDL_Color color_deeppink;
extern SDL_Color color_hotpink;
extern SDL_Color color_lightpink;
extern SDL_Color color_pink;
extern SDL_Color color_mistyrose;
// White variants
extern SDL_Color color_anitquewhite;
extern SDL_Color color_beige;
extern SDL_Color color_bisque;
extern SDL_Color color_blanchedalmond;
extern SDL_Color color_wheat;
extern SDL_Color color_cornsilk;
extern SDL_Color color_lemonchiffon;
extern SDL_Color color_lightgoldenrodyellow;
extern SDL_Color color_lightyellow;
// Brown variants
extern SDL_Color color_saddlebrown;
extern SDL_Color color_sienna;
extern SDL_Color color_chocolate;
extern SDL_Color color_peru;
extern SDL_Color color_sandybrown;
extern SDL_Color color_burlywood;
extern SDL_Color color_tan;
// White variants
extern SDL_Color color_floralwhite;
extern SDL_Color color_ghostwhite;
extern SDL_Color color_ivory;
extern SDL_Color color_snow;
extern SDL_Color color_whitesmoke;
// Grey variants
extern SDL_Color color_dimgray;
extern SDL_Color color_lightgray;
extern SDL_Color color_gainsboro;
extern SDL_Color color_darkgray;

// Others
extern SDL_Color color_rosybrown;
extern SDL_Color color_linen;
extern SDL_Color color_oldlace;
extern SDL_Color color_papayawhip;
extern SDL_Color color_seashell;
extern SDL_Color color_mintcream;
extern SDL_Color color_slategray;
extern SDL_Color color_lightslategray;

int init_colors(void);
Uint32 color_SDLmapRGB(SDL_PixelFormat *format, SDL_Color color);

#endif